apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: "{{ .Release.Name }}-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: kubedemo
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        env:
          - name: MY_VAR
            value: "From Kubernetes Deployment"